(function(){
'use strict';
const SQRT2PI=Math.sqrt(2*Math.PI);
function pdf(x){return Math.exp(-0.5*x*x)/SQRT2PI;}
function cdf(x){const s=x<0?-1:1,a=Math.abs(x)/Math.sqrt(2),t=1/(1+0.3275911*a);const y=1-(((((1.061405429*t-1.453152027)*t+1.421413741)*t-0.284496736)*t+0.254829592)*t)*Math.exp(-a*a);return .5*(1+s*y);}
function years(v,u){return Number(v)/(u==='years'||u==='年'?1:u==='months'||u==='月'?12:365);}
function bs(S,K,T,r,q,sigma){if(!(S>0&&K>0&&T>0&&sigma>0))throw Error('價格、期限與波動率必須大於 0');const st=Math.sqrt(T),d1=(Math.log(S/K)+(r-q+.5*sigma*sigma)*T)/(sigma*st),d2=d1-sigma*st,eq=Math.exp(-q*T),er=Math.exp(-r*T);return{call:S*eq*cdf(d1)-K*er*cdf(d2),put:K*er*cdf(-d2)-S*eq*cdf(-d1),d1,d2};}
function greeks(S,K,T,r,q,sigma){const p=bs(S,K,T,r,q,sigma),st=Math.sqrt(T),eq=Math.exp(-q*T),er=Math.exp(-r*T),n=pdf(p.d1);return{deltaC:eq*cdf(p.d1),deltaP:-eq*cdf(-p.d1),gamma:eq*n/(S*sigma*st),vega:S*eq*n*st/100,thetaC:(-S*eq*n*sigma/(2*st)-r*K*er*cdf(p.d2)+q*S*eq*cdf(p.d1))/365,thetaP:(-S*eq*n*sigma/(2*st)+r*K*er*cdf(-p.d2)-q*S*eq*cdf(-p.d1))/365,rhoC:K*T*er*cdf(p.d2)/100,rhoP:-K*T*er*cdf(-p.d2)/100};}
function binomial(S,K,T,r,q,sigma,n){n=Math.max(2,Math.min(2000,Math.round(n)));const dt=T/n,u=Math.exp(sigma*Math.sqrt(dt)),d=1/u,p=(Math.exp((r-q)*dt)-d)/(u-d),disc=Math.exp(-r*dt);if(!(p>=0&&p<=1))throw Error('參數使風險中立機率超出 0～1，請調整期數或輸入值');let ec=[],ep=[],ac=[],ap=[];for(let i=0;i<=n;i++){const st=S*Math.pow(u,n-i)*Math.pow(d,i);ec[i]=Math.max(st-K,0);ep[i]=Math.max(K-st,0);ac[i]=ec[i];ap[i]=ep[i];}for(let step=n-1;step>=0;step--){for(let i=0;i<=step;i++){const st=S*Math.pow(u,step-i)*Math.pow(d,i);ec[i]=disc*(p*ec[i]+(1-p)*ec[i+1]);ep[i]=disc*(p*ep[i]+(1-p)*ep[i+1]);ac[i]=Math.max(st-K,disc*(p*ac[i]+(1-p)*ac[i+1]));ap[i]=Math.max(K-st,disc*(p*ap[i]+(1-p)*ap[i+1]));}}return{euCall:ec[0],euPut:ep[0],amCall:ac[0],amPut:ap[0],u,d,p};}
function binomialGreeks(S,K,T,r,q,sigma,n){const b=binomial(S,K,T,r,q,sigma,n),h=Math.max(S*.01,.01),up=binomial(S+h,K,T,r,q,sigma,n),dn=binomial(Math.max(.0001,S-h),K,T,r,q,sigma,n),vu=binomial(S,K,T,r,q,sigma+.01,n),ru=binomial(S,K,T,r+.01,q,sigma,n),tn=binomial(S,K,Math.max(T-1/365,1e-6),r,q,sigma,n);const out={base:b};for(const [tag,key] of [['EuC','euCall'],['EuP','euPut'],['AmC','amCall'],['AmP','amPut']]){out['delta'+tag]=(up[key]-dn[key])/(2*h);out['gamma'+tag]=(up[key]-2*b[key]+dn[key])/(h*h);out['vega'+tag]=vu[key]-b[key];out['theta'+tag]=tn[key]-b[key];out['rho'+tag]=ru[key]-b[key];}return out;}
function randn(){let u=0,v=0;while(!u)u=Math.random();while(!v)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}
function mc(S,K,T,r,q,sigma,N,steps,anti){if(!(S>0&&K>0&&T>0&&sigma>0))throw Error('價格、期限與波動率必須大於 0');N=Math.max(100,Math.min(500000,Math.round(N)));steps=Math.max(1,Math.min(500,Math.round(steps)));const dt=T/steps,dr=(r-q-.5*sigma*sigma)*dt,vol=sigma*Math.sqrt(dt),calls=[],puts=[],unitsC=[],unitsP=[],passes=anti?Math.ceil(N/2):N;for(let i=0;i<passes;i++){let a=S,b=S;for(let j=0;j<steps;j++){const z=randn();a*=Math.exp(dr+vol*z);if(anti)b*=Math.exp(dr-vol*z);}const ca=Math.max(a-K,0),pa=Math.max(K-a,0);calls.push(ca);puts.push(pa);if(anti&&calls.length<N){const cb=Math.max(b-K,0),pb=Math.max(K-b,0);calls.push(cb);puts.push(pb);unitsC.push((ca+cb)/2);unitsP.push((pa+pb)/2);}else{unitsC.push(ca);unitsP.push(pa);}}const mean=a=>a.reduce((x,y)=>x+y,0)/a.length,se=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((x,y)=>x+(y-m)**2,0)/(a.length-1))/Math.sqrt(a.length)},disc=Math.exp(-r*T),cm=mean(calls),pm=mean(puts);return{callPrice:disc*cm,putPrice:disc*pm,callStd:disc*se(unitsC),putStd:disc*se(unitsP),samples:calls.length,independentUnits:unitsC.length};}
function iv(price,S,K,T,r,q,type){if(!(price>0))return{error:'市場價格必須大於 0'};const lower=type==='call'?Math.max(S*Math.exp(-q*T)-K*Math.exp(-r*T),0):Math.max(K*Math.exp(-r*T)-S*Math.exp(-q*T),0),upper=type==='call'?S*Math.exp(-q*T):K*Math.exp(-r*T);if(price<lower-1e-8||price>upper+1e-8)return{error:`市場價格超出無套利區間 ${lower.toFixed(4)}～${upper.toFixed(4)}`};const f=s=>(type==='call'?bs(S,K,T,r,q,s).call:bs(S,K,T,r,q,s).put)-price;let s=Math.max(.01,Math.min(5,Math.sqrt(2*Math.PI/T)*price/S));for(let i=0;i<60;i++){const diff=f(s);if(Math.abs(diff)<1e-8)return{sigma:s,iter:i+1,residual:diff,method:'Newton-Raphson'};const v=S*Math.exp(-q*T)*pdf((Math.log(S/K)+(r-q+.5*s*s)*T)/(s*Math.sqrt(T)))*Math.sqrt(T);if(v<1e-12)break;const next=s-diff/v;if(!(next>0&&next<10))break;s=next;}let lo=1e-6,hi=5,fl=f(lo),fh=f(hi);while(fl*fh>0&&hi<50){hi*=2;fh=f(hi);}if(fl*fh>0)return{error:'找不到合理的隱含波動率'};for(let i=0;i<200;i++){const mid=(lo+hi)/2,fm=f(mid);if(Math.abs(fm)<1e-10)return{sigma:mid,iter:i+1,residual:fm,method:'Bisection'};if(fl*fm<=0){hi=mid;fh=fm;}else{lo=mid;fl=fm;}}const mid=(lo+hi)/2;return{sigma:mid,iter:200,residual:f(mid),method:'Bisection'};}
function fmt(x,d=4){return Number.isFinite(x)?Number(x).toFixed(d):'—';}
window.OptionsMath={pdf,cdf,years,bs,greeks,binomial,binomialGreeks,mc,iv,fmt};
})();
