const M=OptionsMath,tabs=document.querySelectorAll('.strategy-tabs .page-tab'),form=document.querySelector('#strategyForm'),title=document.querySelector('#strategyTitle'),badge=document.querySelector('#strategyBadge'),box=document.querySelector('#resultBox');let current='single',chart=null;
const names={single:'單一部位',covered:'避險部位',straddle:'跨式策略',spread:'價差策略',synthetic:'合成期貨',butterfly:'蝶式 Butterfly',condor:'兀鷹 Iron Condor'};
const field=(id,label,val,step='1')=>`<div class="form-row"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="number" step="${step}" required></div>`;
function common(S=75,lo=50,hi=100){return `${field('spotPrice','資產價格 S',S,'.1')}${field('xMin','X 軸下界',lo,'.1')}${field('xMax','X 軸上界',hi,'.1')}`}
function renderForm(){let h='';if(current==='single')h=`<div class="form-row"><label>類型</label><select id="positionType"><option value="longCall">買權（Long Call）</option><option value="longPut">賣權（Long Put）</option><option value="shortCall">賣出買權（Short Call）</option><option value="shortPut">賣出賣權（Short Put）</option></select></div>${field('K','履約價 K',75,'.1')}${field('premium','權利金',4.5,'.1')}${common()}`;
else if(current==='covered')h=`<div class="form-row"><label>策略</label><select id="positionType"><option value="protective">保護性賣權</option><option value="coveredCall">掩護性買權</option></select></div>${field('K','履約價 K',75,'.1')}${field('premium','選擇權權利金',4.5,'.1')}${common()}`;
else if(current==='straddle')h=`<div class="form-row"><label>方向</label><select id="positionType"><option value="long">買進跨式／勒式</option><option value="short">賣出跨式／勒式</option></select></div>${field('Kc','Call 履約價',75,'.1')}${field('Kp','Put 履約價',75,'.1')}${field('premiumC','Call 權利金',4.5,'.1')}${field('premiumP','Put 權利金',4.2,'.1')}<div class="form-hint">兩個履約價不同時即為勒式策略。</div>${common()}`;
else if(current==='spread')h=`<div class="form-row"><label>類型</label><select id="positionType"><option value="bullCall">多頭買權價差</option><option value="bearPut">空頭賣權價差</option><option value="bullPut">多頭賣權價差</option><option value="bearCall">空頭買權價差</option></select></div>${field('K1','低履約價 K₁',65)}${field('K2','高履約價 K₂',80)}${field('premium1','低履約權利金',11,'.1')}${field('premium2','高履約權利金',4,'.1')}${common()}`;
else if(current==='synthetic')h=`<div class="form-row"><label>方向</label><select id="positionType"><option value="long">合成多頭</option><option value="short">合成空頭</option></select></div>${field('K','履約價 K',75)}${field('premiumC','Call 權利金',4.5,'.1')}${field('premiumP','Put 權利金',4.2,'.1')}${common()}`;
else if(current==='butterfly')h=`<div class="form-row"><label>方向</label><select id="positionType"><option value="long">買入蝶式</option><option value="short">賣出蝶式</option></select></div>${field('K1','低履約 K₁',70)}${field('K2','中履約 K₂',75)}${field('K3','高履約 K₃',80)}${field('premium1','K₁ 權利金',7,'.1')}${field('premium2','K₂ 權利金',4.5,'.1')}${field('premium3','K₃ 權利金',2.5,'.1')}${common(75,60,90)}`;
else h=`<div class="form-row"><label>方向</label><select id="positionType"><option value="short">賣出兀鷹（看盤整）</option><option value="long">買入兀鷹（看突破）</option></select></div>${field('K1','K₁ 買 Put',60)}${field('K2','K₂ 賣 Put',70)}${field('K3','K₃ 賣 Call',80)}${field('K4','K₄ 買 Call',90)}${field('premium1','K₁ Put 權利金',1,'.1')}${field('premium2','K₂ Put 權利金',3,'.1')}${field('premium3','K₃ Call 權利金',3.2,'.1')}${field('premium4','K₄ Call 權利金',1.2,'.1')}${common()}`;
form.innerHTML=`<div class="dynamic-fields">${h}</div><div class="form-actions"><button class="solid-btn" type="submit">繪圖</button><button class="outline-btn" type="reset">清除</button></div>`;form.onsubmit=e=>{e.preventDefault();draw()};form.onreset=()=>setTimeout(renderForm,0)}
const v=id=>+document.getElementById(id).value;function payoff(leg,ST){let x=leg.type==='call'?Math.max(ST-leg.K,0):leg.type==='put'?Math.max(leg.K-ST,0):ST-leg.K;return leg.qty*(x-leg.premium)}
function legs(){const t=document.getElementById('positionType').value;if(current==='single'){const map={longCall:['call',1],longPut:['put',1],shortCall:['call',-1],shortPut:['put',-1]},m=map[t];return[{type:m[0],K:v('K'),qty:m[1],premium:v('premium')}]};if(current==='covered'){const opt=t==='protective'?{type:'put',K:v('K'),qty:1,premium:v('premium')}:{type:'call',K:v('K'),qty:-1,premium:v('premium')};return[{type:'stock',K:v('spotPrice'),qty:1,premium:0},opt]};if(current==='straddle'){const q=t==='long'?1:-1;return[{type:'call',K:v('Kc'),qty:q,premium:v('premiumC')},{type:'put',K:v('Kp'),qty:q,premium:v('premiumP')}]};if(current==='spread'){const K1=v('K1'),K2=v('K2'),p1=v('premium1'),p2=v('premium2');if(t==='bullCall')return[{type:'call',K:K1,qty:1,premium:p1},{type:'call',K:K2,qty:-1,premium:p2}];if(t==='bearPut')return[{type:'put',K:K2,qty:1,premium:p2},{type:'put',K:K1,qty:-1,premium:p1}];if(t==='bullPut')return[{type:'put',K:K1,qty:1,premium:p1},{type:'put',K:K2,qty:-1,premium:p2}];return[{type:'call',K:K2,qty:1,premium:p2},{type:'call',K:K1,qty:-1,premium:p1}]};if(current==='synthetic'){const q=t==='long'?1:-1;return[{type:'call',K:v('K'),qty:q,premium:v('premiumC')},{type:'put',K:v('K'),qty:-q,premium:v('premiumP')}]};if(current==='butterfly'){const q=t==='long'?1:-1;return[{type:'call',K:v('K1'),qty:q,premium:v('premium1')},{type:'call',K:v('K2'),qty:-2*q,premium:v('premium2')},{type:'call',K:v('K3'),qty:q,premium:v('premium3')}]};const q=t==='short'?1:-1;return[{type:'put',K:v('K1'),qty:q,premium:v('premium1')},{type:'put',K:v('K2'),qty:-q,premium:v('premium2')},{type:'call',K:v('K3'),qty:-q,premium:v('premium3')},{type:'call',K:v('K4'),qty:q,premium:v('premium4')}];}
function draw(){try{const lo=v('xMin'),hi=v('xMax'),S=v('spotPrice');if(!(hi>lo))throw Error('X 軸上界必須大於下界');const ls=legs(),xs=[],ys=[];for(let i=0;i<=160;i++){const x=lo+(hi-lo)*i/160;xs.push(x);ys.push(ls.reduce((a,l)=>a+payoff(l,x),0))}const bes=[];for(let i=1;i<ys.length;i++)if(ys[i-1]*ys[i]<=0&&ys[i-1]!==ys[i]){const t=-ys[i-1]/(ys[i]-ys[i-1]);bes.push(xs[i-1]+t*(xs[i]-xs[i-1]))}box.className='';box.innerHTML='<div class="chart-canvas-wrap"><canvas id="strategyChart"></canvas></div><div id="strategySummary"></div>';chart?.destroy();chart=new Chart(document.querySelector('#strategyChart'),{type:'line',data:{labels:xs.map(x=>x.toFixed(2)),datasets:[{label:'到期損益',data:ys,borderColor:'#a96a46',backgroundColor:'rgba(230,169,130,.14)',fill:{target:{value:0}},pointRadius:0,borderWidth:2.5,tension:0}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},scales:{x:{title:{display:true,text:'到期標的價格 Sₜ'},ticks:{maxTicksLimit:10}},y:{title:{display:true,text:'到期損益'}}},plugins:{legend:{display:false}}}});const max=Math.max(...ys),min=Math.min(...ys),cur=ys.reduce((best,y,i)=>Math.abs(xs[i]-S)<Math.abs(xs[best]-S)?i:best,0);document.querySelector('#strategySummary').innerHTML=`<div class="summary-grid"><div class="summary-cell"><span>區間內最大獲利</span><strong>${M.fmt(max,2)}</strong></div><div class="summary-cell"><span>區間內最大損失</span><strong>${M.fmt(min,2)}</strong></div><div class="summary-cell"><span>損益兩平點</span><strong>${bes.length?bes.map(x=>x.toFixed(2)).join('、'):'—'}</strong></div><div class="summary-cell"><span>目前價格 S₀</span><strong>${M.fmt(S,2)}</strong></div><div class="summary-cell"><span>S₀ 對應損益</span><strong>${M.fmt(ys[cur],2)}</strong></div><div class="summary-cell"><span>策略腿數</span><strong>${ls.length}</strong></div></div>`}catch(e){box.className='error-box';box.textContent=e.message}}
function select(t){current=t.dataset.strategy;tabs.forEach(x=>x.classList.toggle('active',x===t));title.textContent=names[current];badge.textContent=names[current];renderForm();box.className='chart-placeholder';box.innerHTML='<div class="chart-grid"><div class="chart-zero-line"></div><div class="chart-spot-line"></div><div class="chart-empty-copy"><strong>等待繪圖</strong><small>輸入參數後按「繪圖」</small></div></div><div class="chart-x-label">到期日標的價格 S_T</div>'}tabs.forEach(t=>t.onclick=()=>select(t));renderForm();
